---
#################################################################################
# Copyright (c) 2020 WANdisco
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Apache License, Version 2.0
#
################################################################################
#
# This docker-compose.yml file will bring up an HDP sandbox vanilla extended cluster

version: "3.7"

services:
  sandbox-hdp-vanilla:
    ports:
      - "8081:8081"
      - "18080:18080"
