#################################################################################
# Copyright (c) 2014-2019 WANdisco
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Apache License, Version 2.0
#
################################################################################
#
# This docker-compose.yml file creates all WANdisco Fusion services needed to
# for running in an HDP zone.
#
# Services running in each zone
#     Zone
#         Fusion NameNode Proxy (fusion-nn-proxy)
#         Fusion UI Server HDP  (fusion-ui-server-${ZONE_NAME})
#         Fusion IHC Server     (fusion-ihc-server-${ZONE_NAME})
#         Fusion Server         (fusion-server-${ZONE_NAME})
#
# Note: while version 3.7 is technically compatible with Docker 18.06 and
# higher, this project was tested with only Docker 18.09 as of 2019-08-06.

version: "3.7"

services:
  debug:
    image: ubuntu
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - logging-server-${ZONE_NAME}:/debug/server-${ZONE_NAME}
      - logging-ui-server-${ZONE_NAME}:/debug/ui-server-${ZONE_NAME}
      - logging-ihc-${ZONE_NAME}:/debug/ihc-server-${ZONE_NAME}
      - logging-npx-${ZONE_NAME}:/debug/npx-${ZONE_NAME}
    networks:
      - fusion

  # Fusion NameNode Proxy (NPX)
  fusion-nn-proxy-${ZONE_NAME}:
    image: wandisco/fusion-nn-proxy-${PLATFORM}:${FUSION_NN_PROXY_VERSION}-${FUSION_NN_PROXY_IMAGE_RELEASE}
    restart: unless-stopped
    depends_on:
      - fusion-server-${ZONE_NAME}
    networks:
      - fusion
    env_file:
      - "${ZONE_ENV}"
    ports:
      - ${FUSION_NAME_NODE_PROXY_PORT}:${FUSION_NAME_NODE_PROXY_PORT}
    volumes:
      - logging-npx-${ZONE_NAME}:/var/log/fusion
      - fusion-${ZONE_NAME}-etc-wandisco:/etc/wandisco
      - fusion-${ZONE_NAME}-etc-hadoop:/etc/hadoop
      - config_files/krb5.conf:/etc/krb5.conf

  # Fusion UI Server
  fusion-ui-server-${ZONE_NAME}:
    image: wandisco/fusion-ui-server-${PLATFORM}:${FUSION_BASE_VERSION}-${FUSION_IMAGE_RELEASE}
    restart: unless-stopped
    depends_on:
      - fusion-server-${ZONE_NAME}
    networks:
      - fusion
    ports:
      - ${FUSION_UI_SERVER_PORT}:${FUSION_UI_SERVER_PORT}
      - ${FUSION_UI_SERVER_PORT_TLS}:${FUSION_UI_SERVER_PORT_TLS}
    env_file:
      - "${ZONE_ENV}"
    volumes:
      - logging-ui-server-${ZONE_NAME}:/var/log/fusion
      - fusion-${ZONE_NAME}-opt-wandisco-fusion-server-checkpoint:/opt/wandisco/fusion/server/checkpoint
      - fusion-${ZONE_NAME}-opt-wandisco-fusion-server-dcone:/opt/wandisco/fusion/server/dcone
      - fusion-${ZONE_NAME}-opt-wandisco-fusion-ui-server-properties:/opt/wandisco/fusion-ui-server/properties
      - fusion-${ZONE_NAME}-etc-wandisco:/etc/wandisco
      - fusion-${ZONE_NAME}-etc-hadoop:/etc/hadoop
      - config_files/krb5.conf:/etc/krb5.conf
      ${LICENSE_FILE_PATH}

  # Fusion IHC Server
  fusion-ihc-server-${ZONE_NAME}:
    image: wandisco/fusion-ihc-server-${PLATFORM}:${FUSION_BASE_VERSION}-${FUSION_IMAGE_RELEASE}
    restart: unless-stopped
    depends_on:
      - fusion-server-${ZONE_NAME}
    env_file:
      - "${ZONE_ENV}"
    networks:
      - fusion
    ports:
      - ${FUSION_IHC_SERVER_PORT}:${FUSION_IHC_SERVER_PORT}
      - ${FUSION_IHC_SERVER_JMX_PORT}:${FUSION_IHC_SERVER_JMX_PORT}
    volumes:
      - logging-ihc-${ZONE_NAME}:/var/log/fusion
      - fusion-${ZONE_NAME}-opt-wandisco-fusion-server-checkpoint:/opt/wandisco/fusion/server/checkpoint
      - fusion-${ZONE_NAME}-etc-wandisco:/etc/wandisco
      - fusion-${ZONE_NAME}-etc-hadoop:/etc/hadoop
      - config_files/krb5.conf:/etc/krb5.conf
      - fusion-${ZONE_NAME}-restart:/restart
      ${LICENSE_FILE_PATH}

  # Fusion Server
  fusion-server-${ZONE_NAME}:
    image: wandisco/fusion-server-${PLATFORM}:${FUSION_BASE_VERSION}-${FUSION_IMAGE_RELEASE}
    restart: unless-stopped
    networks:
      - fusion
    ports:
      - ${FUSION_SERVER_HDFS_PORT}:${FUSION_SERVER_HDFS_PORT}
      - ${FUSION_SERVER_TLS_PORT}:${FUSION_SERVER_TLS_PORT}
      - ${FUSION_SERVER_IHC_LISTENER_PORT}:${FUSION_SERVER_IHC_LISTENER_PORT}
      - ${FUSION_SERVER_PORT}:${FUSION_SERVER_PORT}
    env_file:
      - "${ZONE_ENV}"
    volumes:
      - logging-server-${ZONE_NAME}:/var/log/fusion
      - fusion-${ZONE_NAME}-opt-wandisco-fusion-server-checkpoint:/opt/wandisco/fusion/server/checkpoint
      - fusion-${ZONE_NAME}-opt-wandisco-fusion-server-dcone:/opt/wandisco/fusion/server/dcone
      - fusion-${ZONE_NAME}-etc-wandisco:/etc/wandisco
      - fusion-${ZONE_NAME}-etc-hadoop:/etc/hadoop
      - config_files/krb5.conf:/etc/krb5.conf
      - fusion-${ZONE_NAME}-restart:/restart
      - fusion-${ZONE_NAME}-opt-wandisco-fusion-ui-server-properties:/opt/wandisco/fusion-ui-server/properties
      ${LICENSE_FILE_PATH}

networks:
  # One Docker network is shared between both zones
  fusion: {}

volumes:
  # The named logging volumes for all components
  logging-server-${ZONE_NAME}:
  logging-ui-server-${ZONE_NAME}:
  logging-ihc-${ZONE_NAME}:
  logging-npx-${ZONE_NAME}:

  # Checkpoint volume (confirm if this is needed to persist across container restarts)
  fusion-${ZONE_NAME}-opt-wandisco-fusion-server-checkpoint:

  # dcone volume to persist database changes across restarts
  fusion-${ZONE_NAME}-opt-wandisco-fusion-server-dcone:

  # volumes for persisting config
  fusion-${ZONE_NAME}-etc-wandisco:
  fusion-${ZONE_NAME}-etc-hadoop:
  fusion-${ZONE_NAME}-opt-wandisco-fusion-ui-server-properties:
