---
#################################################################################
# Copyright (c) 2014-2019 WANdisco
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Apache License, Version 2.0
#
################################################################################
#
# This docker-compose.yml file will bring up an HDP sandbox cluster

version: "3.7"

services:
  sandbox-hdp:
    image: wandisco/sandbox-hdp:2.15.1.2-4
    privileged: true
    command: ["/sbin/init"]
    env_file: sandbox.env
    ports:
      - "8080:8080"
      - "50070:50070"
      - "50010:50010"
    networks:
      - fusion
    hostname: sandbox-hdp
    ulimits:
      nproc: 800000
      nofile:
        soft: 170000
        hard: 190000

  fusion-server-sandbox-hdp:
    depends_on:
      - sandbox-hdp
