---
#################################################################################
# Copyright (c) 2014-2020 WANdisco
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Apache License, Version 2.0
#
################################################################################
#
# This docker-compose.yml file will bring up an CDH sandbox cluster

version: "3.7"

services:
  sandbox-cdh:
    image: wandisco/sandbox-cdh:2.15.2.1-1
    privileged: true
    command: ["/sbin/init"]
    env_file: sandbox.env
    ports:
      - "7180:7180"
      - "8889:8889"
      - "50070:50070"
      - "50010:50010"
    external_links:
      - fusion-server-${ZONE_NAME}:fusion-server-sandbox-cdh
      - fusion-livehive-proxy-${ZONE_NAME}:fusion-livehive-proxy-sandbox-cdh
    networks:
      - fusion
    hostname: sandbox-cdh
    ulimits:
      nproc: 800000
      nofile:
        soft: 170000
        hard: 190000

  fusion-server-${ZONE_NAME}:
    depends_on:
      - sandbox-cdh
