#################################################################################
# Copyright (c) 2014-2019 WANdisco
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Apache License, Version 2.0
#
################################################################################
#
# This docker-compose.yml file creates all WANdisco Fusion services needed to
# stand up an HDI zone.
#
# Services running in each zone
#     Zone
#         Fusion UI Server HDI  (fusion-ui-server-${ZONE_NAME})
#         Fusion IHC Server     (fusion-ihc-server-${ZONE_NAME})
#         Fusion Server         (fusion-server-${ZONE_NAME})
#
# Note: while version 3.7 is technically compatible with Docker 18.06 and
# higher, this project was tested with only Docker 18.09 as of 2019-08-06.

version: "3.7"

services:
  debug:
    image: ubuntu
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - logging-${ZONE_NAME}:/debug/${ZONE_NAME}
    networks:
      - fusion

  # Fusion UI Server
  fusion-ui-server-${ZONE_NAME}:
    image: wandisco/fusion-ui-server-${PLATFORM}:${FUSION_BASE_VERSION}-${FUSION_IMAGE_RELEASE}
    depends_on:
      - fusion-server-${ZONE_NAME}
    networks:
      - fusion
    ports:
      - ${FUSION_UI_SERVER_PORT}:${FUSION_UI_SERVER_PORT}
      - ${FUSION_UI_SERVER_PORT_TLS}:${FUSION_UI_SERVER_PORT_TLS}
    restart: unless-stopped
    env_file:
      - "${ZONE_ENV}"
    volumes:
      - logging-${ZONE_NAME}:/var/log/fusion
      - fusion-${ZONE_NAME}-opt-wandisco-fusion-server-checkpoint:/opt/wandisco/fusion/server/checkpoint
      - fusion-${ZONE_NAME}-opt-wandisco-fusion-server-dcone:/opt/wandisco/fusion/server/dcone
      - fusion-${ZONE_NAME}-opt-wandisco-fusion-ui-server-properties:/opt/wandisco/fusion-ui-server/properties
      - fusion-${ZONE_NAME}-etc-wandisco:/etc/wandisco
      - fusion-${ZONE_NAME}-hdfs-home-aws:/home/hdfs/.aws

  # Fusion IHC Server
  fusion-ihc-server-${ZONE_NAME}:
    image: wandisco/fusion-ihc-server-${PLATFORM}:${FUSION_BASE_VERSION}-${FUSION_IMAGE_RELEASE}
    depends_on:
      - fusion-server-${ZONE_NAME}
    networks:
      - fusion
    # Note: standard ports have been incremented by 500 to remove conflicts between Zone 1 and Zone 2
    ports:
      - ${FUSION_IHC_SERVER_PORT}:${FUSION_IHC_SERVER_PORT}
      - ${FUSION_IHC_SERVER_PORT_TLS}:${FUSION_IHC_SERVER_PORT_TLS}
      - ${FUSION_IHC_SERVER_JMX_PORT}:${FUSION_IHC_SERVER_JMX_PORT}
    restart: unless-stopped
    env_file:
      - "${ZONE_ENV}"
    volumes:
      - logging-${ZONE_NAME}:/var/log/fusion
      - fusion-${ZONE_NAME}-opt-wandisco-fusion-server-checkpoint:/opt/wandisco/fusion/server/checkpoint
      - fusion-${ZONE_NAME}-etc-wandisco:/etc/wandisco
      - fusion-${ZONE_NAME}-hdfs-home-aws:/home/hdfs/.aws
      - fusion-${ZONE_NAME}-restart:/var/run/wandisco/ihc

  # Fusion Server
  fusion-server-${ZONE_NAME}:
    image: wandisco/fusion-server-${PLATFORM}:${FUSION_BASE_VERSION}-${FUSION_IMAGE_RELEASE}
    networks:
      - fusion
    # Note: standard ports have been incremented by 500 to remove conflicts between Zone 1 and Zone 2
    ports:
      - ${FUSION_SERVER_IHC_LISTENER_PORT}:${FUSION_SERVER_IHC_LISTENER_PORT}
      - ${FUSION_SERVER_HDFS_PORT}:${FUSION_SERVER_HDFS_PORT}
      - ${FUSION_SERVER_PORT}:${FUSION_SERVER_PORT}
      - ${FUSION_SERVER_TLS_PORT}:${FUSION_SERVER_TLS_PORT}
      - ${FUSION_REPLICATION_PORT}:${FUSION_REPLICATION_PORT}
    restart: unless-stopped
    environment:
      - DB_ACTION=
    env_file:
      - "${ZONE_ENV}"
    volumes:
      - logging-${ZONE_NAME}:/var/log/fusion
      - fusion-${ZONE_NAME}-opt-wandisco-fusion-server-checkpoint:/opt/wandisco/fusion/server/checkpoint
      - fusion-${ZONE_NAME}-opt-wandisco-fusion-server-dcone:/opt/wandisco/fusion/server/dcone
      - fusion-${ZONE_NAME}-hdfs-home-aws:/home/hdfs/.aws
      - fusion-${ZONE_NAME}-opt-wandisco-fusion-ui-server-properties:/opt/wandisco/fusion-ui-server/properties
      - fusion-${ZONE_NAME}-etc-wandisco:/etc/wandisco
      - fusion-${ZONE_NAME}-restart:/var/run/wandisco/ihc

networks:
  # One Docker network is shared between both zones
  fusion: {}

volumes:
  # The named logging volumes for all components
  logging-${ZONE_NAME}:

  # Checkpoint volume (confirm if this is needed to persist across container restarts)
  fusion-${ZONE_NAME}-opt-wandisco-fusion-server-checkpoint:

  # dcone volume to persist database changes across restarts
  fusion-${ZONE_NAME}-opt-wandisco-fusion-server-dcone:

  # volumes for persisting config
  fusion-${ZONE_NAME}-etc-wandisco:
  fusion-${ZONE_NAME}-hdfs-home-aws:
  fusion-${ZONE_NAME}-opt-wandisco-fusion-ui-server-properties:
