#################################################################################
# Copyright (c) 2014-2019 WANdisco
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Apache License, Version 2.0
#
################################################################################
#
# Note: while version 3.7 is technically compatible with Docker 18.06 and
# higher, this project was tested with only Docker 18.09 as of 2019-08-06.
#
################################################################################

version: "3.7"

services:
  # This service performs the induction process as a Docker container job at launch.
  induction:
    image: wandisco/fusion-server-${PLATFORM}:${FUSION_BASE_VERSION}-${FUSION_IMAGE_RELEASE}
    networks:
      - fusion
    environment:
      - INDUCTOR=fusion-server-${ZONE_A_NAME}
      - INDUCTEE=fusion-server-${ZONE_B_NAME}
      - INDUCTOR_PORT=${ZONE_A_SERVER_PORT}
      - INDUCTEE_PORT=${ZONE_B_SERVER_PORT}
      - INDUCTEE_REPLICATION_PORT=${ZONE_B_REPLICATION_PORT}
    command: /scripts/induction.sh